In [2]:
import pandas as pd

In [3]:
X_train = pd.read_csv("mortality/X_train.csv", index_col=[0], header=[0, 1, 2])
X_train

LEVEL2               alanine aminotransferase                                \
Aggregation Function                     mask
hours_in                                    0    1    2    3    4    5    6
3_145834_211552                           1.0  0.0  0.0  0.0  0.0  0.0  0.0
6_107064_228232                           1.0  0.0  0.0  0.0  0.0  0.0  0.0
9_150750_220597                           0.0  0.0  0.0  0.0  0.0  0.0  0.0
11_194540_229441                          0.0  0.0  0.0  0.0  0.0  0.0  0.0
12_112213_232669                          0.0  0.0  0.0  0.0  0.0  0.0  0.0
...                                       ...  ...  ...  ...  ...  ...  ...
99966_167228_252173                       0.0  0.0  0.0  0.0  0.0  0.0  0.0
99973_150202_275083                       0.0  0.0  0.0  0.0  0.0  0.0  0.0
99982_151454_221194                       0.0  0.0  0.0  0.0  0.0  0.0  0.0
99991_151118_226241                       0.0  0.0  0.0  0.0  0.0  0.0  0.0
99995_137810_229633                       0.0  1.0  1.0  0.0  0.0  0.0  0.0

LEVEL2                               ... white blood cell count urine         \
Aggregation Function                 ...          time_since_measured
hours_in                7    8    9  ...                           14     15
3_145834_211552       0.0  0.0  0.0  ...                          6.0    7.0
6_107064_228232       0.0  0.0  0.0  ...                         30.0   31.0
9_150750_220597       0.0  0.0  0.0  ...                         54.0   55.0
11_194540_229441      0.0  0.0  0.0  ...                         78.0   79.0
12_112213_232669      0.0  0.0  0.0  ...                        102.0  103.0
...                   ...  ...  ...  ...                          ...    ...
99966_167228_252173   0.0  0.0  0.0  ...                         86.0   87.0
99973_150202_275083   0.0  0.0  0.0  ...                        110.0  111.0
99982_151454_221194   0.0  0.0  0.0  ...                        134.0  135.0
99991_151118_226241   0.0  0.0  0.0  ...                         14.0   15.0
99995_137810_229633   0.0  0.0  0.0  ...                         38.0   39.0

LEVEL2
Aggregation Function
hours_in                 16     17     18     19     20     21     22     23
3_145834_211552         8.0    9.0   10.0   11.0   12.0   13.0   14.0   15.0
6_107064_228232        32.0   33.0   34.0   35.0   36.0   37.0   38.0   39.0
9_150750_220597        56.0   57.0   58.0   59.0   60.0   61.0   62.0   63.0
11_194540_229441       80.0   81.0   82.0   83.0   84.0   85.0   86.0   87.0
12_112213_232669      104.0  105.0  106.0  107.0  108.0  109.0  110.0  111.0
...                     ...    ...    ...    ...    ...    ...    ...    ...
99966_167228_252173    88.0   89.0   90.0   91.0   92.0   93.0   94.0   95.0
99973_150202_275083   112.0  113.0  114.0  115.0  116.0  117.0  118.0  119.0
99982_151454_221194   136.0  137.0  138.0  139.0  140.0  141.0  142.0  143.0
99991_151118_226241    16.0   17.0   18.0   19.0   20.0   21.0   22.0   23.0
99995_137810_229633    40.0   41.0   42.0   43.0   44.0   45.0   46.0   47.0

[16760 rows x 7488 columns]

In [5]:
Y_train_2 = pd.read_csv("LoS/Y_train.csv")
Y_train_2

                Unnamed: 0   los_icu
0          3_145834_211552  6.064560
1          6_107064_228232  3.672917
2          9_150750_220597  5.323056
3         11_194540_229441  1.584410
4         12_112213_232669  7.634815
...                    ...       ...
16755  99966_167228_252173  1.703391
16756  99973_150202_275083  2.731933
16757  99982_151454_221194  7.949259
16758  99991_151118_226241  3.142616
16759  99995_137810_229633  2.161481

[16760 rows x 2 columns]